{
 "title": "ArangoDB Oasis Deployment",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Agency Log Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "arangodb_agency_log_size_bytes", "legendFormat": "{{server}}" }
   ]
  },
  {
   "title": "Slow queries count increase",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(arangodb_aql_slow_query[5m])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Agency write to not leader",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(agency_agent_write_no_leader[15m])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Total number of AQL queries(increase)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(arangodb_aql_all_query[5m])"
    }
   ]
  },
  {
   "title": "AQL total query time(increase)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "increase(arangodb_aql_total_query_time_msec[5m])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Scheduler threads worker/working",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "arangodb_scheduler_num_worker_threads ",
     "legendFormat": "{{server}}"
    },
    {
     "expr": "arangodb_scheduler_num_working_threads",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Scheduler threads started/stopped",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(arangodb_scheduler_threads_started[5m])",
     "legendFormat": "{{server}}"
    },
    {
     "expr": "- increase(arangodb_scheduler_threads_stopped[5m])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Scheduler queue length",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "arangodb_scheduler_queue_length",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "V8 contexts max/free",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "arangodb_v8_context_max", "legendFormat": "{{server}} (max)" },
    { "expr": "arangodb_v8_context_free", "legendFormat": "{{server}} (free)" }
   ]
  },
  {
   "title": "Scheduler jobs submitted/dequeued",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(arangodb_scheduler_jobs_submitted[5m])",
     "legendFormat": "{{server}}"
    },
    {
     "expr": "- increase(arangodb_scheduler_jobs_dequeued[5m])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Maintenance action failure counter",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "arangodb_maintenance_action_failure_counter",
     "legendFormat": "{{action}},{{server}}"
    }
   ]
  },
  {
   "title": "Scheduler jobs done",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(arangodb_scheduler_jobs_done[5m])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Resident Set Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "arangodb_process_statistics_resident_set_size",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Shards out of sync",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "arangodb_shards_out_of_sync", "legendFormat": "{{server}}" }
   ]
  },
  {
   "title": "Virtual Memory Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "arangodb_process_statistics_virtual_memory_size",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Process System Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(arangodb_process_statistics_system_time[1m])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Process User Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(arangodb_process_statistics_user_time[1m])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Number of Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "arangodb_process_statistics_number_of_threads",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Client connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "arangodb_client_connection_statistics_client_connections",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Major Page Faults Rate 5m",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(arangodb_process_statistics_major_page_faults[5m])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Minor Page Faults Rate 5m",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(arangodb_process_statistics_minor_page_faults[5m])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Requests rate [1m]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(arangodb_http_request_statistics_total_requests[1m])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "GET requests [5m]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(arangodb_http_request_statistics_http_get_requests[5m])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "POST/PUT/PATCH requests [5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(arangodb_http_request_statistics_http_post_requests[5m])",
     "legendFormat": "{{server}}-POST"
    },
    {
     "expr": "rate(arangodb_http_request_statistics_http_put_requests[5m])",
     "legendFormat": "{{server}}-PUT"
    },
    {
     "expr": "rate(arangodb_http_request_statistics_http_patch_requests[5m])",
     "legendFormat": "{{server}}-PATCH"
    }
   ]
  },
  {
   "title": "DELETE requests [5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(arangodb_http_request_statistics_http_delete_requests[5m])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "RocksDB cache allocate [5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(rocksdb_cache_allocated[5m])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "RocksDB throttle bps [5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(rocksdbengine_throttle_bps[5m])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "RocksDB cache hit rate recent [5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(rocksdb_cache_hit_rate_recent[5m])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "RocksDB actual delayed write rate [5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(rocksdb_actual_delayed_write_rate[5m])",
     "legendFormat": "{{server}}"
    }
   ]
  }
 ]
}